language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1KoltLaby
  - make -j
 # - cd ./bin/
  - ./VectorTest/TestVector
  - ./MatrixTest/TestMatrix
  - ./StackTest/TestStack
  - ./QueueTest/TestQueue
notifications:
  email: false
