language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1KoltLaby
  - make -j
 # - cd ./bin/
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./StackTest/StackTest
  - ./QueueTest/QueueTest
  - ./ArrListTest/ArrListTest
   - ./ListTest/ListTest
notifications:
  email: false
